---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/dolph/docker-image-google-cloud
- name: weekly
  type: time
  source:
    interval: 168h
- name: image
  type: docker-image
  source:
    repository: dolphm/ubuntu-google-cloud
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}

jobs:
- name: build-image
  serial: true
  build_logs_to_retain: 3
  plan:
  - get: repo
    trigger: true
  - get: weekly
    trigger: true
  - put: image
    attempts: 1
    params:
      build: repo/docker
